# MySQL DB
CREATE TABLE angola.trackinghistory (
  THID int(11) NOT NULL AUTO_INCREMENT,
  TRANSACTION_ID varchar(255) DEFAULT NULL,
  --LIGHT_WEIGHT_TIME_STAMP timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
 --LOAD_WEIGHT_TIME_STAMP timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  FINAL_DATE timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  RECORD_STATUS  varchar(1) DEFAULT NULL,
  PRIMARY KEY (THID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
--or 
CREATE TABLE angola.TRACKINGHISTORY (
  THID int(11) NOT NULL AUTO_INCREMENT,
  TRANSACTION_ID varchar(255) DEFAULT NULL,
  LIGHT_WEIGHT_TIME_STAMP varchar(255) DEFAULT NULL,
  LOAD_WEIGHT_TIME_STAMP varchar(255) DEFAULT NULL,
  FINAL_DATE timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  RECORD_STATUS  varchar(1) DEFAULT NULL,
  PRIMARY KEY (THID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


# Oracle DB
CREATE TABLE XXSSGIL_WB_TRIP_DTLS(
    TRIP_NO INT,
    LIGHT_WT_TIMESTAMP TIMESTAMP,
    LOAD_WT_TIMESTAMP TIMESTAMP,
    LIGHT_WT_BY VARCHAR2(100),
    LOAD_WT_BY VARCHAR2(100),
    LOAD_WT_IN_KG INT,
    LIGHT_WT_IN_KG INT
)


# MsSQL DB
CREATE TABLE XXSSGIL_WB_INTEGRATION (
    TRANSACTION_ID INT primary key,
    TRIP_NUMBER INT,
    LIGHT_WT_IN_KG INT,
    LIGHT_WEIGHT_TIME_STAMP DATETIME,
    LOAD_WT_IN_KG INT,
    LOAD_WEIGHT_TIME_STAMP DATETIME,
    LIGHT_WEIGHT_BY VARCHAR(100),  
    LOAD_WEIGHT_BY VARCHAR(100),  
    second_LIGHT_WEIGHT INT ,
    CREATE_BY VARCHAR(100),
    CREATE_DATE DATETIME,
    UPDATE_BY VARCHAR(100),
    UPDATE_DATE DATETIME,
    TOLERANCE_WEIGHT VARCHAR(50),
    ATTRIBUTE1 VARCHAR(100),
    ATTRIBUTE2 VARCHAR(100),
    ATTRIBUTE3 VARCHAR(100),
    ATTRIBUTE6 INT,
    ATTRIBUTE7 INT,
    ATTRIBUTE8 INT,
    ATTRIBUTE10 DATETIME,
    ATTRIBUTE11 DATETIME
)

-- Some sample data to insert ino MsSQL DB
INSERT INTO XXSSGIL_WB_INTEGRATION 
    (TRANSACTION_ID,
    TRIP_NUMBER,
    LIGHT_WT_IN_KG,
    LIGHT_WEIGHT_TIME_STAMP,
    LOAD_WT_IN_KG,
    LOAD_WEIGHT_TIME_STAMP,
    LIGHT_WEIGHT_BY,
    LOAD_WEIGHT_BY,
    second_LIGHT_WEIGHT,
    CREATE_BY,
    CREATE_DATE,
    UPDATE_BY,
    UPDATE_DATE)
VALUES 
    ('1',
    '10662960',
    '14000',
     NULL,
    '8500',
     NULL,
    '1603',
    '1603',
     NULL,
    '1603',
    '2020-12-12 18:00:00',
    '1603',
    '2020-12-12 18:00:00');


INSERT INTO XXSSGIL_WB_INTEGRATION 
    (TRANSACTION_ID,
    TRIP_NUMBER,
    LIGHT_WT_IN_KG,
    LIGHT_WEIGHT_TIME_STAMP,
    LOAD_WT_IN_KG,
    LOAD_WEIGHT_TIME_STAMP,
    LIGHT_WEIGHT_BY,
    LOAD_WEIGHT_BY,
    second_LIGHT_WEIGHT,
    CREATE_BY,
    CREATE_DATE,
    UPDATE_BY,
    UPDATE_DATE)
VALUES 
    ('2',
    '10662960',
    '14000',
     NULL,
    '8500',
     NULL,
    '1603',
    '1603',
     NULL,
    '1603',
    '2020-12-12 18:10:00',
    '1603',
    '2020-12-12 18:10:00');


INSERT INTO XXSSGIL_WB_INTEGRATION 
    (TRANSACTION_ID,
    TRIP_NUMBER,
    LIGHT_WT_IN_KG,
    LIGHT_WEIGHT_TIME_STAMP,
    LOAD_WT_IN_KG,
    LOAD_WEIGHT_TIME_STAMP,
    LIGHT_WEIGHT_BY,
    LOAD_WEIGHT_BY,
    second_LIGHT_WEIGHT,
    CREATE_BY,
    CREATE_DATE,
    UPDATE_BY,
    UPDATE_DATE)
VALUES 
    ('3',
    '10662960',
    '14000',
     NULL,
    '8500',
     NULL,
    '1603',
    '1603',
     NULL,
    '1603',
    '2020-12-12 18:20:00',
    '1603',
    '2020-12-12 18:20:00');

INSERT INTO XXSSGIL_WB_INTEGRATION 
    (TRANSACTION_ID,
    TRIP_NUMBER,
    LIGHT_WT_IN_KG,
    LIGHT_WEIGHT_TIME_STAMP,
    LOAD_WT_IN_KG,
    LOAD_WEIGHT_TIME_STAMP,
    LIGHT_WEIGHT_BY,
    LOAD_WEIGHT_BY,
    second_LIGHT_WEIGHT,
    CREATE_BY,
    CREATE_DATE,
    UPDATE_BY,
    UPDATE_DATE)
VALUES 
    ('4',
    '10662960',
    '14000',
     NULL,
    '8500',
     NULL,
    '1603',
    '1603',
     NULL,
    '1603',
    '2020-12-12 18:30:00',
    '1603',
    '2020-12-12 18:30:00');